from .samplers import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_samplers, 
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_samplers
    )

NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS_samplers, 
    }

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS_samplers,
    }

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
