from .nodes.guider import GUIDER_CLASS_MAPPINGS, GUIDER_NAME_MAPPINGS
from .nodes.samplers import SAMPLERS_CLASS_MAPPINGS, SAMPLERS_NAME_MAPPINGS
from .nodes.models import MODELS_CLASS_MAPPINGS, MODELS_NAME_MAPPINGS


NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(GUIDER_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GUIDER_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(SAMPLERS_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SAMPLERS_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(MODELS_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MODELS_NAME_MAPPINGS)


__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
